// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: errors_reason/errors_reason.proto

package errors_reason

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// Set the error code separately for an enumeration.
	ErrorReason_INTERNAL_SERVER_ERROR ErrorReason = 0
	ErrorReason_USER_NOT_FOUND        ErrorReason = 1
	ErrorReason_CONTENT_MISSING       ErrorReason = 2
	ErrorReason_BAD_REQUEST           ErrorReason = 3
	ErrorReason_UNAUTHORIZED          ErrorReason = 4
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "INTERNAL_SERVER_ERROR",
		1: "USER_NOT_FOUND",
		2: "CONTENT_MISSING",
		3: "BAD_REQUEST",
		4: "UNAUTHORIZED",
	}
	ErrorReason_value = map[string]int32{
		"INTERNAL_SERVER_ERROR": 0,
		"USER_NOT_FOUND":        1,
		"CONTENT_MISSING":       2,
		"BAD_REQUEST":           3,
		"UNAUTHORIZED":          4,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_reason_errors_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_errors_reason_errors_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_errors_reason_errors_reason_proto_rawDescGZIP(), []int{0}
}

var File_errors_reason_errors_reason_proto protoreflect.FileDescriptor

var file_errors_reason_errors_reason_proto_rawDesc = []byte{
	0x0a, 0x21, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x11, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x5f,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x98, 0x01, 0x0a, 0x0b,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x15, 0x49,
	0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45, 0xf4, 0x03, 0x12, 0x18, 0x0a, 0x0e,
	0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01,
	0x1a, 0x04, 0xa8, 0x45, 0x94, 0x03, 0x12, 0x19, 0x0a, 0x0f, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e,
	0x54, 0x5f, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x1a, 0x04, 0xa8, 0x45, 0xa6,
	0x03, 0x12, 0x15, 0x0a, 0x0b, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x10, 0x03, 0x1a, 0x04, 0xa8, 0x45, 0x90, 0x03, 0x12, 0x16, 0x0a, 0x0c, 0x55, 0x4e, 0x41, 0x55,
	0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x04, 0x1a, 0x04, 0xa8, 0x45, 0x91, 0x03,
	0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x2b, 0x5a, 0x29, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x72, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x5f, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x3b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x5f, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_errors_reason_errors_reason_proto_rawDescOnce sync.Once
	file_errors_reason_errors_reason_proto_rawDescData = file_errors_reason_errors_reason_proto_rawDesc
)

func file_errors_reason_errors_reason_proto_rawDescGZIP() []byte {
	file_errors_reason_errors_reason_proto_rawDescOnce.Do(func() {
		file_errors_reason_errors_reason_proto_rawDescData = protoimpl.X.CompressGZIP(file_errors_reason_errors_reason_proto_rawDescData)
	})
	return file_errors_reason_errors_reason_proto_rawDescData
}

var file_errors_reason_errors_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_reason_errors_reason_proto_goTypes = []interface{}{
	(ErrorReason)(0), // 0: api.errors_reason.ErrorReason
}
var file_errors_reason_errors_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_reason_errors_reason_proto_init() }
func file_errors_reason_errors_reason_proto_init() {
	if File_errors_reason_errors_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_errors_reason_errors_reason_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_reason_errors_reason_proto_goTypes,
		DependencyIndexes: file_errors_reason_errors_reason_proto_depIdxs,
		EnumInfos:         file_errors_reason_errors_reason_proto_enumTypes,
	}.Build()
	File_errors_reason_errors_reason_proto = out.File
	file_errors_reason_errors_reason_proto_rawDesc = nil
	file_errors_reason_errors_reason_proto_goTypes = nil
	file_errors_reason_errors_reason_proto_depIdxs = nil
}
