// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.2
// - protoc             v3.21.12
// source: v1/seller/seller.proto

package seller

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSellerSelf = "/api.v1.auth.seller.Seller/Self"

type SellerHTTPServer interface {
	Self(context.Context, *SelfRequest) (*SelfReply, error)
}

func RegisterSellerHTTPServer(s *http.Server, srv SellerHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/auth/sellers/self", _Seller_Self0_HTTP_Handler(srv))
}

func _Seller_Self0_HTTP_Handler(srv SellerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SelfRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSellerSelf)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Self(ctx, req.(*SelfRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SelfReply)
		return ctx.Result(200, reply)
	}
}

type SellerHTTPClient interface {
	Self(ctx context.Context, req *SelfRequest, opts ...http.CallOption) (rsp *SelfReply, err error)
}

type SellerHTTPClientImpl struct {
	cc *http.Client
}

func NewSellerHTTPClient(client *http.Client) SellerHTTPClient {
	return &SellerHTTPClientImpl{client}
}

func (c *SellerHTTPClientImpl) Self(ctx context.Context, in *SelfRequest, opts ...http.CallOption) (*SelfReply, error) {
	var out SelfReply
	pattern := "/v1/auth/sellers/self"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSellerSelf))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
